server:
  port: 8080

spring:
  application:
    name: medialabo

  datasource:
    url: jdbc:mysql://patient-db:3306/medialabo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: medialabo
    password: medialabo
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ou 'validate' selon ton besoin
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # 🔥 Empêche toute tentative de config Mongo dans ce microservice
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.medialabo: DEBUG