server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # ⚠️ Par compat, on met aussi les default-filters au niveau "classique"
      default-filters:
        - AddRequestHeader=Authorization, Basic b3JnYW5pemVyOmNoYW5nZWl0

      server:
        webflux:
          routes:
            # --------- NOTE-SERVICE (8080) ----------
            - id: notes-by-patient-exact
              order: -10
              uri: http://note-service:8080
              predicates:
                - Path=/api/patients/{id}/notes
              filters:
                - AddRequestHeader=Authorization, Basic b3JnYW5pemVyOmNoYW5nZWl0

            - id: notes-by-patient-suffix
              order: -9
              uri: http://note-service:8080
              predicates:
                - Path=/api/patients/{id}/notes/**
              filters:
                - AddRequestHeader=Authorization, Basic b3JnYW5pemVyOmNoYW5nZWl0

            - id: notes-search
              order: -8
              uri: http://note-service:8080
              predicates:
                - Path=/api/notes/**
              filters:
                - AddRequestHeader=Authorization, Basic b3JnYW5pemVyOmNoYW5nZWl0

            # --------- RISK-SERVICE (8080) ----------
            - id: risk-service
              order: -5
              uri: http://risk-service:8080
              predicates:
                - Path=/api/risk/**
              filters:
                - AddRequestHeader=Authorization, Basic b3JnYW5pemVyOmNoYW5nZWl0

            # --------- PATIENT-SERVICE (8080) : catch-all ----------
            - id: patient-service
              order: 0
              uri: http://patient-service:8080
              predicates:
                - Path=/api/**
              filters:
                - AddRequestHeader=Authorization, Basic b3JnYW5pemVyOmNoYW5nZWl0

          # CORS si le front (8080) appelle la Gateway (8081)
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: ["http://front-service:8080","http://localhost:8080"]
                allowed-methods: [GET, POST, PUT, DELETE, OPTIONS]
                allowed-headers: ["*"]
                allow-credentials: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info