server:
  port: 8080

spring:
  application:
    name: note-service
  data:
    mongodb:
      uri: mongodb://mongo:27017/MediaLabo

management:
  endpoints:
    web:
      exposure:
        include: health,info